name: queen
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # webf: ^0.12.0+1
  dio: ^4.0.6 #網路框架
  shared_preferences: ^2.0.15 #本地緩存
  fluttertoast: ^8.0.9 #toast,由裝置下方出現的提示信息
  json_annotation: ^4.5.0 #json模板
  flutter_spinkit: ^5.1.0 #loading框樣式
  path_provider: ^2.0.10 #本地路徑
  flutter_screenutil: ^5.5.3+2 #固定字體大小，不被裝置系統字體影響
  event_bus: ^2.0.0 #事件管理
  connectivity_plus: ^2.3.0 #網路
  url_launcher: ^6.1.2 #啟動外部瀏覽器
  provider: ^6.0.3 #狀態管理
  share_plus: ^4.0.4 #分享
  intl: ^0.17.0 #日期格式化
  webview_flutter: ^3.0.4 #webvivew
  device_info_plus: ^4.0.0 #設備資訊
  sqflite: ^2.0.2+1 #資料庫
  overlay_support: ^2.0.1 #類似推播提醒
  flutter_svg: ^1.1.5 #svg
  intl_phone_field: ^3.1.0 #國際電話區碼
  flutter_localized_locales: ^2.0.3 #多語言
  socket_io_client: ^2.0.0 #socket io聊天室
  flutter_webrtc: ^0.9.11 #通訊
  live_flutter_plugin: ^1.0.16 #騰訊直播
  flutter_styled_toast: ^2.0.0
  adaptive_action_sheet: ^2.0.1
  crypto: ^3.0.2 #加解密
  hive: ^2.2.3 #數據持久化
  hive_flutter: ^1.1.0 #hive擴充

dev_dependencies:
  json_serializable: ^6.2.0 #json模板
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.10.0 #產生icon
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Application/
    - assets/images/Login/
    - assets/images/注册/
    - assets/images/Tabbar/icon_tabbar_video/
    - assets/images/Tabbar/icon_tabbar_video_sel/
    - assets/images/Tabbar/icon_tabbar_realhome/
    - assets/images/Tabbar/icon_tabbar_realhome_sel/
    - assets/images/Tabbar/icon_tabbar_profile_sel/
    - assets/images/Tabbar/icon_tabbar_profile/
    - assets/images/Tabbar/icon_tabbar_live_sel/
    - assets/images/Tabbar/icon_tabbar_live/
    - assets/images/Tabbar/icon_tabbar_game_sel/
    - assets/images/Tabbar/icon_tabbar_game/
    - assets/images/HomePage/home_testbanner/
    - assets/images/HomePage/livecorner/
    - assets/images/HomePage/home_message/
    - assets/images/girls/
  

  generate: true

flutter_icons:
  image_path: "assets/images/Application/icon-1024.png"
  android: "launcher_icon" # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"