// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'liveUser.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

LiveUser _$LiveUserFromJson(Map<String, dynamic> json) => LiveUser(
      isdnd: json['isdnd'] as String,
      fans: json['fans'] as String,
      id: json['id'] as String,
      country: json['country'] as String,
      level: json['level'] as String,
      bgImg: json['bg_img'] as String,
      avatarThumb: json['avatar_thumb'] as String,
      votes: json['votes'] as String,
      liveStatus: json['live_status'] as int,
      singleAnswer: json['single_answer'] as String,
      votestotal: json['votestotal'] as String,
      coin: json['coin'] as String,
      levelAnchor: json['level_anchor'] as String,
      sex: json['sex'] as String,
      userLogin: json['user_login'] as String,
      videoCount: json['video_count'] as String,
      birthday: json['birthday'] as String,
      singleSwitch: json['single_switch'] as String,
      city: json['city'] as String,
      avatar: json['avatar'] as String,
      lastConn: json['last_conn'] as String,
      lives: json['lives'] as int,
      userNicename: json['user_nicename'] as String,
      consumption: json['consumption'] as String,
      province: json['province'] as String,
      singleCharge: json['single_charge'] as String,
      follows: json['follows'] as String,
      userAuth: json['user_auth'] as int,
      authVideo: json['auth_video'] as String,
      constellation: json['constellation'] as String,
      liang: json['liang'] as Map<String, dynamic>,
      liveAuth: json['live_auth'] as String,
      money: json['money'] as int,
      signature: json['signature'] as String,
      singleImg: json['single_img'] as String,
      singleRefuse: json['single_refuse'] as String,
      vip: json['vip'] as Map<String, dynamic>,
    );

Map<String, dynamic> _$LiveUserToJson(LiveUser instance) => <String, dynamic>{
      'isdnd': instance.isdnd,
      'fans': instance.fans,
      'id': instance.id,
      'country': instance.country,
      'level': instance.level,
      'bg_img': instance.bgImg,
      'avatar_thumb': instance.avatarThumb,
      'votes': instance.votes,
      'live_status': instance.liveStatus,
      'single_answer': instance.singleAnswer,
      'votestotal': instance.votestotal,
      'coin': instance.coin,
      'level_anchor': instance.levelAnchor,
      'sex': instance.sex,
      'user_login': instance.userLogin,
      'video_count': instance.videoCount,
      'birthday': instance.birthday,
      'single_switch': instance.singleSwitch,
      'city': instance.city,
      'avatar': instance.avatar,
      'last_conn': instance.lastConn,
      'lives': instance.lives,
      'user_nicename': instance.userNicename,
      'consumption': instance.consumption,
      'province': instance.province,
      'single_charge': instance.singleCharge,
      'follows': instance.follows,
      'user_auth': instance.userAuth,
      'signature': instance.signature,
      'constellation': instance.constellation,
      'single_img': instance.singleImg,
      'single_refuse': instance.singleRefuse,
      'live_auth': instance.liveAuth,
      'auth_video': instance.authVideo,
      'money': instance.money,
      'vip': instance.vip,
      'liang': instance.liang,
    };
