// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'videoList.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

VideoList _$VideoListFromJson(Map<String, dynamic> json, t) => VideoList(
      id: json['id'] as String,
      uid: json['uid'] as String,
      typeId: json['type_id'] as String,
      title: json['title'] as String,
      thumb: json['thumb'] as String,
      thumbS: json['thumb_s'] as String,
      href: json['href'] as String,
      likes: json['likes'] as String,
      views: json['views'] as String,
      comments: json['comments'] as String,
      steps: json['steps'] as String,
      shares: json['shares'] as String,
      addtime: json['addtime'] as String,
      lat: json['lat'] as String,
      lng: json['lng'] as String,
      city: json['city'] as String,
      isdel: json['isdel'] as String,
      status: json['status'] as String,
      musicId: json['music_id'] as String,
      xiajiaReason: json['xiajia_reason'] as String?,
      showVal: json['show_val'] as String,
      nopassTime: json['nopass_time'] as String,
      watchOk: json['watch_ok'] as String,
      isAd: json['is_ad'] as String,
      adEndtime: json['typad_endtimee'] as String?,
      adUrl: json['ad_url'] as String?,
      orderno: json['orderno'] as String,
      isShopping: json['is_shopping'] as String,
      isHot: json['is_hot'] as String,
      videoUserInfo:
          VideoUserInfo.fromJson(json['userinfo'] as Map<String, dynamic>),
      datetime: json['datetime'] as String,
      islike: json['islike'] as String,
      isstep: json['isstep'] as String,
      isattent: json['isattent'] as String,
      tag: json['tag'] as int,
    );

Map<String, dynamic> _$VideoListToJson(VideoList instance) => <String, dynamic>{
      'id': instance.id,
      'uid': instance.uid,
      'type_id': instance.typeId,
      'title': instance.title,
      'thumb': instance.thumb,
      'thumb_s': instance.thumbS,
      'href': instance.href,
      'likes': instance.likes,
      'views': instance.views,
      'comments': instance.comments,
      'steps': instance.steps,
      'shares': instance.shares,
      'addtime': instance.addtime,
      'lat': instance.lat,
      'lng': instance.lng,
      'city': instance.city,
      'isdel': instance.isdel,
      'status': instance.status,
      'music_id': instance.musicId,
      'xiajia_reason': instance.xiajiaReason,
      'show_val': instance.showVal,
      'nopass_time': instance.nopassTime,
      'watch_ok': instance.watchOk,
      'is_ad': instance.isAd,
      'typad_endtimee': instance.adEndtime,
      'ad_url': instance.adUrl,
      'orderno': instance.orderno,
      'is_shopping': instance.isShopping,
      'is_hot': instance.isHot,
      'userinfo': instance.videoUserInfo.toJson(),
      'datetime': instance.datetime,
      'islike': instance.islike,
      'isstep': instance.isstep,
      'isattent': instance.isattent,
      'tag': instance.tag,
    };

VideoUserInfo _$VideoUserInfoFromJson(Map<String, dynamic> json) =>
    VideoUserInfo(
      id: json['id'] as String,
      userLogin: json['user_login'] as String,
      userNicename: json['user_nicename'] as String,
      avatar: json['avatar'] as String,
      avatarThumb: json['avatar_thumb'] as String,
      sex: json['sex'] as String,
      signature: json['signature'] as String,
      coin: json['coin'] as String,
      consumption: json['consumption'] as String,
      votestotal: json['votestotal'] as String,
      province: json['province'] as String,
      city: json['city'] as String,
      birthday: json['birthday'] as String,
      userStatus: json['user_status'] as String,
      issuper: json['issuper'] as String,
      bgImg: json['bg_img'] as String,
      singleSwitch: json['single_switch'] as String,
      constellation: json['constellation'] as String,
      singleRefuse: json['single_refuse'] as String,
      singleAnswer: json['single_answer'] as String,
      singleCharge: json['single_charge'] as String,
      lastConn: json['last_conn'] as String,
      liveStatus: json['live_status'],
      level: json['level'] as String,
      levelAnchor: json['level_anchor'] as String,
    );

Map<String, dynamic> _$VideoUserInfoToJson(VideoUserInfo instance) =>
    <String, dynamic>{
      'id': instance.id,
      'user_login': instance.userLogin,
      'user_nicename': instance.userNicename,
      'avatar': instance.avatar,
      'avatar_thumb': instance.avatarThumb,
      'sex': instance.sex,
      'signature': instance.signature,
      'coin': instance.coin,
      'consumption': instance.consumption,
      'votestotal': instance.votestotal,
      'province': instance.province,
      'city': instance.city,
      'birthday': instance.birthday,
      'user_status': instance.userStatus,
      'issuper': instance.issuper,
      'bg_img': instance.bgImg,
      'single_switch': instance.singleSwitch,
      'constellation': instance.constellation,
      'single_refuse': instance.singleRefuse,
      'single_answer': instance.singleAnswer,
      'single_charge': instance.singleCharge,
      'last_conn': instance.lastConn,
      'live_status': instance.liveStatus,
      'level': instance.level,
      'level_anchor': instance.levelAnchor,
    };
